version: '3.9'


services:
  db:
    image: postgres:14.1-alpine3.15
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: netology
